# Generated by Django 3.1.3 on 2021-03-12 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0003_auto_20210312_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='GEOID',
            field=models.CharField(db_column='GEOID', max_length=10),
        ),
        migrations.CreateModel(
            name='CountySubdivisionPolygon',
            fields=[
                ('PolygonID', models.OneToOneField(db_column='PolygonID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ahj_app.polygon')),
                ('LSAreaCodeName', models.CharField(db_column='LSAreaCodeName', max_length=100)),
                ('StatePolygonID', models.ForeignKey(db_column='StatePolygonID', on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.statepolygon')),
            ],
            options={
                'db_table': 'CountySubdivisionPolygon',
                'managed': True,
            },
        ),
    ]
