# Generated by Django 3.1.3 on 2021-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0006_ahjusermaintains_engineeringreviewrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringreviewrequirement',
            name='EngineeringReviewRequirementStatus',
            field=models.IntegerField(db_column='EngineeringReviewRequirementStatus', default=False),
            preserve_default=False,
        ),
    ]
