# Generated by Django 3.1.3 on 2021-04-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0007_engineeringreviewrequirement_engineeringreviewrequirementstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ahjinspection',
            name='TechnicianRequired',
            field=models.BooleanField(db_column='TechnicianRequired', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='AHJPK',
            field=models.IntegerField(db_column='AHJPK', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='AddressID',
            field=models.ForeignKey(db_column='AddressID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Latitude',
            field=models.DecimalField(db_column='Latitude', decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='Longitude',
            field=models.DecimalField(db_column='Longitude', decimal_places=8, max_digits=11, null=True),
        ),
    ]
