# Generated by Django 3.1.3 on 2021-05-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0008_auto_20210430_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('AddressTypeID', models.AutoField(db_column='AddressTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Mailing', 'Mailing'), ('Billing', 'Billing'), ('Installation', 'Installation'), ('Shipping', 'Shipping')], db_column='Value', max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AHJCensusName',
            fields=[
                ('AHJPK', models.OneToOneField(db_column='AHJPK', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ahj_app.ahj')),
                ('AHJCensusName', models.CharField(db_column='AHJCensusName', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AHJLevelCode',
            fields=[
                ('AHJLevelCodeID', models.AutoField(db_column='AHJLevelCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('040', 'State'), ('050', 'State County'), ('061', 'State County Minor Civil Division'), ('162', 'State Incorporated Place')], db_column='Value', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingCode',
            fields=[
                ('BuildingCodeID', models.AutoField(db_column='BuildingCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('2021IBC', '2021 IBC'), ('2018IBC', '2018 IBC'), ('2015IBC', '2015 IBC'), ('2012IBC', '2012 IBC'), ('2009IBC', '2009 IBC'), ('NoSolarRegulations', 'No Solar Regulations')], db_column='Value', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('ContactTypeID', models.AutoField(db_column='ContactTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Homeowner', 'Homeowner'), ('OffTaker', 'Off Taker'), ('Inspector', 'Inspector'), ('Engineer', 'Engineer'), ('Originator', 'Originator'), ('Installer', 'Installer'), ('Investor', 'Investor'), ('PermittingOfficial', 'Permitting Official'), ('FireMarshal', 'Fire Marshal'), ('ProjectManager', 'Project Manager'), ('Salesperson', 'Salesperson')], db_column='Value', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricCode',
            fields=[
                ('ElectricCodeID', models.AutoField(db_column='ElectricCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('2020NEC', '2020 NEC'), ('2017NEC', '2017 NEC'), ('2014NEC', '2014 NEC'), ('2011NEC', '2011 NEC'), ('2008NEC', '2008 NEC'), ('NoSolarRegulations', 'No Solar Regulations')], db_column='Value', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringReviewType',
            fields=[
                ('EngineeringReviewTypeID', models.AutoField(db_column='EngineeringReviewTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('StructuralEngineer', 'Structural Engineer'), ('ElectricalEngineer', 'Electrical Engineer'), ('PVEngineer', 'PV Engineer'), ('MasterElectrician', 'Master Electrician'), ('FireMarshal', 'Fire Marshal'), ('EnvironmentalEngineer', 'Environmental Engineer')], db_column='Value', max_length=21, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureType',
            fields=[
                ('FeeStructureTypeID', models.AutoField(db_column='FeeStructureTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Flat', 'Flat'), ('SystemSize', 'System Size')], db_column='Value', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FireCode',
            fields=[
                ('FireCodeID', models.AutoField(db_column='FireCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('2021IFC', '2021 IFC'), ('2018IFC', '2018 IFC'), ('2015IFC', '2015 IFC'), ('2012IFC', '2012 IFC'), ('2009IFC', '2009 IFC'), ('NoSolarRegulations', 'No Solar Regulations')], db_column='Value', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('InspectionTypeID', models.AutoField(db_column='InspectionTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('RoughIn', 'Rough In'), ('Final', 'Final'), ('Windstorm', 'Windstorm'), ('Electrical', 'Electrical'), ('Structural', 'Structural')], db_column='Value', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationDeterminationMethod',
            fields=[
                ('LocationDeterminationMethodID', models.AutoField(db_column='LocationDeterminationMethodID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('GPS', 'GPS'), ('Survey', 'Survey'), ('AerialImage', 'Aerial Image'), ('EngineeringReport', 'Engineering Report'), ('AddressGeocoding', 'Address Geocoding'), ('Unknown', 'Unknown')], db_column='Value', max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('LocationTypeID', models.AutoField(db_column='LocationTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('DeviceSpecific', 'Device Specific'), ('SiteEntrance', 'Site Entrance'), ('GeneralProximity', 'General Proximity'), ('Warehouse', 'Warehouse')], db_column='Value', max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreferredContactMethod',
            fields=[
                ('PreferredContactMethodID', models.AutoField(db_column='PreferredContactMethodID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Email', 'Email'), ('WorkPhone', 'Work Phone'), ('CellPhone', 'Cell Phone'), ('HomePhone', 'Home Phone'), ('CellTextMessage', 'Cell Text Message')], db_column='Value', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementLevel',
            fields=[
                ('RequirementLevelID', models.AutoField(db_column='RequirementLevelID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Required', 'Required'), ('Optional', 'Optional'), ('ConditionallyRequired', 'Conditionally Required')], db_column='Value', max_length=21, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialCode',
            fields=[
                ('ResidentialCodeID', models.AutoField(db_column='ResidentialCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('2021IRC', '2021 IRC'), ('2018IRC', '2018 IRC'), ('2015IRC', '2015 IRC'), ('2012IRC', '2012 IRC'), ('2009IRC', '2009 IRC'), ('NoSolarRegulations', 'No Solar Regulations')], db_column='Value', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StampType',
            fields=[
                ('StampTypeID', models.AutoField(db_column='StampTypeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('Wet', 'Wet'), ('Digital', 'Digital'), ('Notary', 'Notary'), ('None', 'None')], db_column='Value', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WindCode',
            fields=[
                ('WindCodeID', models.AutoField(db_column='WindCodeID', primary_key=True, serialize=False)),
                ('Value', models.CharField(choices=[('ASCE716', 'ASCE7-16'), ('ASCE710', 'ASCE7-10'), ('ASCE705', 'ASCE7-05'), ('SpecialWindZone', 'Special Wind Zone')], db_column='Value', max_length=15, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ahjinspectioncontact',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ahjinspectioncontact',
            name='ContactID',
        ),
        migrations.RemoveField(
            model_name='ahjinspectioncontact',
            name='InspectionID',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='edit',
            name='InspectionID',
        ),
        migrations.AddField(
            model_name='contact',
            name='ContactStatus',
            field=models.BooleanField(db_column='ContactStatus', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ParentID',
            field=models.IntegerField(db_column='ParentID', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ParentTable',
            field=models.CharField(blank=True, db_column='ParentTable', max_length=255),
        ),
        migrations.AddField(
            model_name='edit',
            name='DataSourceComment',
            field=models.CharField(blank=True, db_column='DataSourceComment', max_length=255),
        ),
        migrations.AddField(
            model_name='edit',
            name='EditType',
            field=models.CharField(db_column='EditType', default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='AddressID',
            field=models.ForeignKey(db_column='AddressID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.address'),
        ),
        migrations.AlterField(
            model_name='ahjdocumentsubmissionmethoduse',
            name='MethodStatus',
            field=models.BooleanField(db_column='MethodStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjinspection',
            name='InspectionStatus',
            field=models.BooleanField(db_column='InspectionStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjpermitissuemethoduse',
            name='MethodStatus',
            field=models.BooleanField(db_column='MethodStatus', null=True),
        ),
        migrations.AlterField(
            model_name='ahjusermaintains',
            name='MaintainerStatus',
            field=models.BooleanField(db_column='MaintainerStatus'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='HomePhone',
            field=models.CharField(blank=True, db_column='HomePhone', max_length=31),
        ),
        migrations.AlterField(
            model_name='contact',
            name='MobilePhone',
            field=models.CharField(blank=True, db_column='MobilePhone', max_length=31),
        ),
        migrations.AlterField(
            model_name='contact',
            name='WorkPhone',
            field=models.CharField(blank=True, db_column='WorkPhone', max_length=31),
        ),
        migrations.AlterField(
            model_name='documentsubmissionmethod',
            name='Value',
            field=models.CharField(choices=[('Epermitting', 'Epermitting'), ('Email', 'Email'), ('InPerson', 'In Person'), ('SolarApp', 'SolarAPP')], db_column='Value', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='AHJPK',
            field=models.ForeignKey(db_column='AHJPK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.ahj'),
        ),
        migrations.AlterField(
            model_name='edit',
            name='NewValue',
            field=models.CharField(blank=True, db_column='NewValue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='OldValue',
            field=models.CharField(blank=True, db_column='OldValue', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='edit',
            name='ReviewStatus',
            field=models.CharField(db_column='ReviewStatus', default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='engineeringreviewrequirement',
            name='EngineeringReviewRequirementStatus',
            field=models.BooleanField(db_column='EngineeringReviewRequirementStatus', null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='FeeStructureStatus',
            field=models.BooleanField(db_column='FeeStructureStatus', null=True),
        ),
        migrations.AlterField(
            model_name='permitissuemethod',
            name='Value',
            field=models.CharField(choices=[('Epermitting', 'Epermitting'), ('Email', 'Email'), ('InPerson', 'In Person'), ('SolarApp', 'SolarAPP')], db_column='Value', max_length=11, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='contact',
            index_together={('ParentTable', 'ParentID')},
        ),
        migrations.DeleteModel(
            name='AHJContactRepresentative',
        ),
        migrations.DeleteModel(
            name='AHJInspectionContact',
        ),
        migrations.AlterField(
            model_name='address',
            name='AddressType',
            field=models.ForeignKey(db_column='AddressType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.addresstype'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='AHJLevelCode',
            field=models.ForeignKey(db_column='AHJLevelCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.ahjlevelcode'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='BuildingCode',
            field=models.ForeignKey(db_column='BuildingCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.buildingcode'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='ElectricCode',
            field=models.ForeignKey(db_column='ElectricCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.electriccode'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='FireCode',
            field=models.ForeignKey(db_column='FireCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.firecode'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='ResidentialCode',
            field=models.ForeignKey(db_column='ResidentialCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.residentialcode'),
        ),
        migrations.AlterField(
            model_name='ahj',
            name='WindCode',
            field=models.ForeignKey(db_column='WindCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.windcode'),
        ),
        migrations.AlterField(
            model_name='ahjinspection',
            name='InspectionType',
            field=models.ForeignKey(db_column='InspectionType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.inspectiontype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ContactType',
            field=models.ForeignKey(db_column='ContactType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.contacttype'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='PreferredContactMethod',
            field=models.ForeignKey(db_column='PreferredContactMethod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.preferredcontactmethod'),
        ),
        migrations.AlterField(
            model_name='engineeringreviewrequirement',
            name='EngineeringReviewType',
            field=models.ForeignKey(db_column='EngineeringReviewType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.engineeringreviewtype'),
        ),
        migrations.AlterField(
            model_name='engineeringreviewrequirement',
            name='RequirementLevel',
            field=models.ForeignKey(db_column='RequirementLevel', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.requirementlevel'),
        ),
        migrations.AlterField(
            model_name='engineeringreviewrequirement',
            name='StampType',
            field=models.ForeignKey(db_column='StampType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.stamptype'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='FeeStructureType',
            field=models.ForeignKey(db_column='FeeStructureType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.feestructuretype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationDeterminationMethod',
            field=models.ForeignKey(db_column='LocationDeterminationMethod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.locationdeterminationmethod'),
        ),
        migrations.AlterField(
            model_name='location',
            name='LocationType',
            field=models.ForeignKey(db_column='LocationType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahj_app.locationtype'),
        ),
    ]