# Generated by Django 3.1.3 on 2021-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahj_app', '0009_v2Migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahjcensusname',
            name='StateProvince',
            field=models.CharField(db_column='StateProvince', default='', max_length=2),
            preserve_default=False,
        ),
    ]
